### ISSUE TITLE
2.0 Planned Changes

### ISSUE THREAD

**Issue by aidantwoods** [aidantwoods/SecureHeaders#19]
There's a lot of work going on under-the-hood, so to speak, to help make SecureHeaders a lot more usable within frameworks. (This thanks to folks like @lucasmichot and @franzliedke).

Since there's going to be a major version bump at some point, I wanted to open up this thread to discuss some feature changes that I'm planning on wrapping into the 2.0 version. This mainly so that there is the opportunity for concerns to be raised that I may have neglected to consider.

1. [x] Better cookie upgrades:
   Specifically incorporating the [`SameSite`](https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1) cookie attribute. The plan is for `SameSite=Lax` to be added in alongside the `HttpOnly` and `Secure` flags to sensitive looking cookies by default, and for this to be upgraded to `SameSite=Strict` if operating in [`strictMode`](https://github.com/aidantwoods/SecureHeaders/wiki/strictMode).

   `SameSite=Lax` already offers pretty good CSRF protection by preventing non GET requests or non top-level requests from sending cookies when coming from a cross-origin source. In other words cookies will not be sent when the request originates from a cross-origin unless request can be seen in the URL bar and any request data is also in the URL bar.

   Obviously this isn't a complete solution, so for those that want it stricter, I'll include the upgrade to `SameSite=Strict` ~~(or just `SameSite` according to spec)~~. This should be able to be configured granularly similarly to how `HttpOnly` and `Secure` are [currently configured](https://github.com/aidantwoods/SecureHeaders/wiki/auto#auto_cookie_secure) or just by enabling `strictMode` to use `SameSite=Strict` (as said above).

2. [x] Add a new header by default:
   The new header being [`X-Permitted-Cross-Domain-Policies: none`](https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#X-Permitted-Cross-Domain-Policies). As with other automatic headers, this will be done via a [header proposal](https://github.com/aidantwoods/SecureHeaders/wiki/header-proposals) – so this can be explicitly removed or modified as you prefer if the default is not desired.

3. [x] I need some feedback on what SecureHeaders should do if you pass it an argument of the wrong type.
   Since generating an exception produces output and forces headers to be sent immediately (preventing already configured ones from being added to PHPs list), there may be a case to do something slightly differently. At present (in 0.0 through to 1.0.1) I've utilised a custom exception class that will trigger the SecureHeaders [`done`](https://github.com/aidantwoods/SecureHeaders/wiki/done) method on your behalf when an exception is uncaught. There has been [some](https://github.com/aidantwoods/SecureHeaders/issues/3#issuecomment-274261704) [discussion](https://github.com/aidantwoods/SecureHeaders/pull/17#issuecomment-272705873) on this perhaps not being the best behaviour because it is unexpected. It would be good to get some feedback on what to do when raising exceptions. Whether that be: "no, don't auto send the headers"; "yes, auto send the headers"; or "it should be user configurable, and the default should be [x]".

4. [x] Add a new header by default: `Referrer-Policy: strict-origin-when-cross-origin` with a fallback policy of `no-referrer`.
   I've made `no-referrer` the fallback because is the only policy value (currently) supported by both Chrome and FF which guarantees that the full query string will remain private on cross-origin requests, and that no URL is leaked over the network on insecure requests (to the same origin).
   At time of writing latest stable on both Chrome and FF do not understand `strict-origin-when-cross-origin` and will use the fallback. Firefox is due to add support in v52. Chrome has a [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=627968) open.
   [Safari and other browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Browser_compatibility) appear to offer no support. This is unfortunate. Hopefully there will be progress.

5. [x] Add a new header by default: `Expect-CT: max-age=0`.
    [Spec here](https://datatracker.ietf.org/doc/draft-stark-expect-ct/).
    This defaults to reporting mode, but will be configurable to operate in enforce mode, or just reporting with some `report-uri` specified.

Thanks for reading! I'll update this issue if I add anything else to the planned changes list 😄

**Comment by craigfrancis** [comment]
Not sure you can do `SameSite` without saying `SameSite=Strict`, as the spec says (in [section 4.1](https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1)):

    If the "attribute-name" case-insensitively matches the string
    "SameSite", the user agent MUST process the "cookie-av" as follows:

    1. If [the] "attribute-value" is not a case-sensitive match
      for "Strict" or "Lax", ignore the "cookie-av".

**Comment by aidantwoods** [comment]
@craigfrancis looks like you're correct there! I think I must've read that last part as `ignore the "attribute-value"` for some reason, and then part 2. makes it look like anything other than `Lax` defaults to `Strict`. I've corrected the above, and I'll make sure to include `Strict` in implementation. Thanks for the heads up! :)

**Comment by craigfrancis** [comment]
You're not the only one, Scott Helme mentioned exactly the same thing 2 weeks ago:

https://scotthelme.co.uk/tough-cookies/
https://crbug.com/635882

And I agree, the second part does make it look like it defaults to `Strict`... which is kind of cool, but I do prefer the more explicit "you must specify" approach (just incase we want to expend what SameSite does at a later date).

:-)

**Comment by aidantwoods** [comment]
I suppose [section 3.1](https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-3.1) also gives the idea that no value is correct. The spec probably needs a bit of a cleanup, then again, it is a draft so 🤷‍♂️ 

```
   cookie-av      = expires-av / max-age-av / domain-av /
                    path-av / secure-av / httponly-av /
                    samesite-av / extension-av
   samesite-av    = "SameSite" / "SameSite=" samesite-value
   samesite-value = "Strict" / "Lax"
```

I think I agree about being explicit in the setting too – among other things it'll read a bit nicer adding `SameSite` as a cookie attribute – code will look similar to the code for existing attributes that can take values (without having to add extra logic to accept no value).

**Comment by craigfrancis** [comment]
The more I read the spec, the more I think your original assumption is correct (that simply saying SameSite with no value should be considered as Strict).

However, Google Chome currently has a bug where the missing value does not work anyway (https://crbug.com/635882).

So even if the spec says it's valid (which I don't think it is perticuarly clear either way), that bug is going to be a problem, and I would prefer everyone to state it clearly anyway :-)

**Comment by aidantwoods** [comment]
Hmm, yeah – I suppose if one were to replace "cookie-av" with "attribute-value" in 1. of section 4.1, then the rest of the spec would make sense.

Also, I'm not entirely sure "ignore the cookie-av" even makes any sense, since it only refers to cookie attributes and not the value. Surely leaving `SameSite` blank should not cause `HttpOnly` and `Secure` to be ignored, but still set the cookie for example...

I think I'll add in support for a blank value in that case, but when SecureHeaders actually injects the `SameSite` attribute (when using `->strictMode()`), perhaps it's best to also explicitly state when it is strict (just so devs can easily see what's going on).

**Comment by craigfrancis** [comment]
Agreed, I think that's the best solution from my point of view (I like these things being explicit).

**Comment by franzliedke** [comment]
Hi Aidan,

my last big refactoring is almost done, and it will make adding these features much simpler - can you hold off on these changes for one or two more days? (I've seen you've already done quite a few.) They just make merging my changes much harder. ;)

**Comment by aidantwoods** [comment]
@franzliedke 

Whoops, yeah sorry about the sudden rush of changes (ran into quite a bit of free time this weekend for the first time in a while!)

Good news is there's not much left to do now, so I'll leave the `2.0` branch alone now for you to work on ;-)

Bar `3.`, everything on this page should already be implemented :D

**Comment by aidantwoods** [comment]
Considering bundling in either 

```
Referrer-Policy: strict-origin-when-cross-origin
```

or 

```
Referrer-Policy: origin-when-cross-origin
```

as another additional header proposal for 2.0.

[spec here](https://www.w3.org/TR/referrer-policy/#referrer-policy-origin-when-cross-origin)

Feedback welcome :)

**Comment by aidantwoods** [comment]
Mainly this would be to attempt to address these points by default (from [spec](https://www.w3.org/TR/referrer-policy/#intro-security)):
> A web application uses HTTPS and a URL-based session identifier. The web application might wish to link to HTTPS resources on other web sites without leaking the user’s session identifier in the URL.

> Alternatively, a web application may use URLs which themselves grant some capability. Controlling the referrer can help prevent these capability URLs from leaking via referrer headers. [[CAPABILITY-URLS]](https://www.w3.org/TR/referrer-policy/#biblio-capability-urls)

**Comment by aidantwoods** [comment]
To address the third point here about exception handling: I think I'm satisfied with having `applyOnOutput` being configurable to auto-send the headers upon the first byte of output to some arbitrary adapter (which includes auto-sending the headers when an exception is encountered).

Since 2.0 has got a lot to do with being integrable with arbitrary frameworks via adapters, I think this is the only behaviour that now makes sense for handling exceptions (since we have no way of knowing the correct place to send the headers unless the user configures it).

I think this gets around the issues @franzliedke raised about the auto-send behaviour being unexpected, since auto-send is entirely the purpose of `applyOnOutput` (and it's not on by default),  I think the behaviour is now pretty expected. But this still allows users to guarantee that headers are processed and sent by SecureHeaders (if they want them to be), which is something I wanted to retain from 1.x.

**Comment by aidantwoods** [comment]
I plan to also add the new (hopefully soon to be supported in major browsers) header `Expect-CT`.

This header can enforce that certificate transparency (CT) is used on all certificated presented for the domain for some defined `max-age` in seconds.

I think it's a good idea to initially set `Expect-CT: max-age=0` so that (when browsers support it) they will start to warn if the CT requirements are not met (presumably in the browser console). Note that by not including the `enforce` directive here, browsers will not enforce and only warn – so there's no risk of causing sites downtime if they don't meet the requirements.

I'll also add a new method to configure `Expect-CT` for higher amounts of time in enforce mode, or in reporting mode with a `report-uri`.

**Comment by aidantwoods** [comment]
#37 implements feature 5, regarding the default `Expect-CT` header.

**Comment by aidantwoods** [comment]
All implemented, release imminent. Closing.

**Comment by franzliedke** [comment]
Congrats!

**Comment by lucasmichot** [comment]
Nice

**Comment by aidantwoods** [comment]
Cheers guys! 🎉 

And a big thank you for all the PRs that've helped get here!

**Comment by aidantwoods** [comment]
Bam!
https://github.com/aidantwoods/SecureHeaders/releases/tag/v2.0
