### ISSUE TITLE
2.0: removeCookies() has no effect

### ISSUE THREAD

**Issue by franzliedke** [aidantwoods/SecureHeaders#23]
This method does not result in an operation being added to the pipeline.

What's needed:
- [x] a unit test for the expected behavior
- [x] a fix

**Comment by aidantwoods** [comment]
Good catch, give me a sec

**Comment by aidantwoods** [comment]
https://github.com/aidantwoods/SecureHeaders/commit/03abafff6730cf72805b88bcfbb8cdabeccddb64

This should fix, made a bit of a mess of copy pasting the test above originally 😬

Can you confirm fix?

**Comment by franzliedke** [comment]
If the test failed without the new code, and now passes, then all should be fine. :)

From a quick glance, the code looks sensible, though.

**Comment by aidantwoods** [comment]
Tests were broken up until that final commit (but did test with/without the new operation)

Asking as I literally walked out the door the second after I did `git push`, maybe I'll give it another test later 😉
