### ISSUE TITLE
Discuss finally releasing 2.0

### ISSUE THREAD

**Issue by aidantwoods** [aidantwoods/SecureHeaders#27]
So everything is #19 is now complete. The documentation can now mostly be very nicely auto-generated from phpdoc. And we now have nice adapters to SecureHeaders can be used in arbitrary frameworks with very minor implementation code.

I'll make some additions to the test suit this weekend just to make sure everything is running nicely and as expected, but other than that I can't think of anything major that needs doing.

@franzliedke @lucasmichot feel free to jump in here if I've forgotten something that needs doing 😜

**Comment by franzliedke** [comment]
Yeah, ensuring with some test cases that all (implicit) behavior of v1.0 still works on 2.0 is my biggest (and only) concern as well. :)

The good thing is that you can still do bug fixes in patch releases, even though they are technically BC-breaking when they just restore behavior that was to be expected from v1.

**Comment by aidantwoods** [comment]
Definitely agree with this :) will make an effort to make sure everything I think should be happening is explicitly documented as well as adding tests in too. So that as you've said: if things aren't happening that are *supposed* to be happening, then we only need a patch release rather than a major version bump.

Will finish up those tests over the next day or so (have been a little sidetracked this week).
