### ISSUE TITLE
Drop support for php5.3, use maybe 5.6 or 7

### ISSUE THREAD

**Issue by prisis** [aidantwoods/SecureHeaders#6]

**Comment by aidantwoods** [comment]
Is there any benefit in dropping 5.3?

I actually developed this in 7 and back-ported it. So everything works up to latest.

**Comment by prisis** [comment]
5.3,5.4,5.5 are not longer supported, only a suggestion :)

**Comment by aidantwoods** [comment]
Apparently those versions are still pretty widely used though:
https://w3techs.com/technologies/details/pl-php/5/all

I'll drop support if it stops me progressing with development, otherwise, might as well support it right? 😀

**Comment by prisis** [comment]
Most of them use Wordpress haha :D

But you win ;)

**Comment by aidantwoods** [comment]
@prisis aha, or just aren't updated, ever 😨
